# Generated by Django 3.1 on 2024-05-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20240509_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand', verbose_name='Marca'),
        ),
    ]
